### ISSUE TITLE
Not all tags are decoded

### ISSUE THREAD

**Issue by roeierez** [fusion44/dart_bolt11_decoder#2]
Thanks a lot for the library!
I have noticed that not all tags are decoded such as "payee pubkey" (identifier 19).
For example in this invoice taken from the example:

lnbc1pvjluezpp5qqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqypqdpl2pkx2ctnv5sxxmmwwd5kgetjypeh2ursdae8g6twvus8g6rfwvs8qun0dfjkxaq8rkx3yf5tcsyz3d73gafnh3cax9rn449d9p5uxz9ezhhypd0elx87sjle52x86fux2ypatgddc6k63n7erqz25le42c4u4ecky03ylcqca784w

**Comment by fusion44** [comment]
Glad you find the library useful! I'll add the missing tags this weekend.

**Comment by fusion44** [comment]
@roeierez I've looked into this today. ID 19 is actually decoded, if present. The example invoice doesn't contain a payee pubkey. You can check that at https://lndecode.com. Other libraries extract the pubkey from the signature and use this as the payee pubkey. I'll add that too and actually implement validating the payment request. Will handle that with #3 

In the process I've discovered that support for extracting `payment_secret` (identifier 16) and `feature_bits` (identifier 5) missing 
 and implemented them accordingly. 

The library returns now returns a TaggedField with type `unknown` instead of null when encountering an unknown tag:

```dart
return TaggedField('unknown tag: $tag', data);
```

**Comment by roeierez** [comment]
@fusion44  Great job! Thank you.
